// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqFExYdvIImhi9VCbpXGMua4ujSINsICM',
    appId: '1:1031932278401:web:e2b3575f9aadc768237f80',
    messagingSenderId: '1031932278401',
    projectId: 'hairstyle-skripsi',
    authDomain: 'hairstyle-skripsi.firebaseapp.com',
    storageBucket: 'hairstyle-skripsi.firebasestorage.app',
    measurementId: 'G-1WR5WK917Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmgOjWfpl9IqqZyx_jIX0pVjGamcaqKzA',
    appId: '1:1031932278401:android:43b75c476ba0c2b9237f80',
    messagingSenderId: '1031932278401',
    projectId: 'hairstyle-skripsi',
    storageBucket: 'hairstyle-skripsi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANzdsNj3YwSwyZvhOzdDKA39TMBTlmlWY',
    appId: '1:1031932278401:ios:d8ccaaa737389ab0237f80',
    messagingSenderId: '1031932278401',
    projectId: 'hairstyle-skripsi',
    storageBucket: 'hairstyle-skripsi.firebasestorage.app',
    iosBundleId: 'com.example.hairstyleApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANzdsNj3YwSwyZvhOzdDKA39TMBTlmlWY',
    appId: '1:1031932278401:ios:d8ccaaa737389ab0237f80',
    messagingSenderId: '1031932278401',
    projectId: 'hairstyle-skripsi',
    storageBucket: 'hairstyle-skripsi.firebasestorage.app',
    iosBundleId: 'com.example.hairstyleApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqFExYdvIImhi9VCbpXGMua4ujSINsICM',
    appId: '1:1031932278401:web:f51c70d00e339a23237f80',
    messagingSenderId: '1031932278401',
    projectId: 'hairstyle-skripsi',
    authDomain: 'hairstyle-skripsi.firebaseapp.com',
    storageBucket: 'hairstyle-skripsi.firebasestorage.app',
    measurementId: 'G-BEYXEYJNBJ',
  );
}
